import type { Metadata, Viewport } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/Toaster'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '600'],
  variable: '--font-poppins',
  display: 'swap',
})

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.vamiclubwear.in'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Vami Clubwear — Women's Fashion in Malappuram, Manjeri | Plus Size, Anarkali, Abaya",
    template: '%s | Vami Clubwear',
  },
  description:
    "Vami Clubwear — premium women's fashion store in Malappuram & Manjeri, Kerala. Plus size & big size aesthetic Anarkalis, abayas, salwars, shararas, churidars, gowns and dupattas up to XXXL. Modest, Malabar wedding & Indo-Western wear, shipped across India.",
  applicationName: 'Vami Clubwear',
  generator: 'Next.js',
  category: 'fashion',
  keywords: [
    // ── Brand & "vami" defence (helps Google associate the query "vami" with this site) ──
    "vami",
    "vami clubwear",
    "vami clubwear manjeri",
    "vami clubwear malappuram",
    "vami clubwear kerala",
    "vami online",
    "vami store",
    "vami fashion",
    "vami women",
    "vami women's wear",
    "vami dress",
    "vami anarkali",
    "vami abaya",
    "vami plus size",
    "vami big size",
    "vami india",
    "vami in",
    "vami.in",
    "vamiclubwear",
    "vamiclubwear.in",
    "vami clubwear online",
    "vami clubwear shop",
    "vami clubwear store",
    "vami clubwear india",
    "vami clubwear official",
    "vami clubwear website",
    "vami official store",
    "vami official website",
    "vami boutique",
    "vami fashion store",
    "vami clothing",
    "vami clothing brand",
    "vami women clothing",
    "vami women fashion",
    "vami brand",
    "vami brand india",
    "vami fashion manjeri",
    "vami fashion malappuram",
    "vami fashion kerala",
    "vami clubwear app",
    "vami clubwear malayalam",
    "vami clubwear instagram",
    "വാമി",
    "വാമി ക്ലബ്‌വെയർ",
    "വാമി മഞ്ചേരി",
    "വാമി ഫാഷൻ",
    "വാമി ഷോപ്പ്",
    "vaami clubwear",
    "vaami manjeri",
    "vamy clubwear",
    "vaami fashion",
    "vami ladies wear",

    // ── Manjeri & Malappuram local SEO (English) ──
    "women's clothing manjeri",
    "ladies wear manjeri",
    "fashion store manjeri",
    "boutique manjeri",
    "dress shop manjeri",
    "women's boutique manjeri",
    "anarkali manjeri",
    "abaya manjeri",
    "plus size shop manjeri",
    "big size shop manjeri",
    "women's clothes malappuram",
    "ladies wear malappuram",
    "women fashion malappuram",
    "fashion store malappuram",
    "boutique malappuram",
    "dress shop malappuram",
    "wedding dress malappuram",
    "plus size malappuram",
    "big size dress malappuram",
    "anarkali malappuram",
    "salwar malappuram",
    "sharara malappuram",
    "churidar malappuram",
    "gown malappuram",
    "lehenga malappuram",
    "abaya malappuram",
    "hijab malappuram",
    "modest wear malappuram",
    "muslim wear malappuram",
    "wedding dress manjeri",
    "nikkah dress manjeri",
    "nikkah dress malappuram",
    "engagement dress manjeri",
    "reception dress manjeri",
    "eid dress manjeri",
    "eid dress malappuram",
    "ramadan dress malappuram",
    "women's online shop malappuram",
    "online dress shop malappuram",
    "online clothing malappuram",
    "women clothing online malappuram",
    "ladies online shopping malappuram",

    // Surrounding towns / talukas
    "women's clothes perinthalmanna",
    "ladies wear perinthalmanna",
    "fashion store perinthalmanna",
    "abaya perinthalmanna",
    "plus size perinthalmanna",
    "women's clothes kondotty",
    "ladies wear kondotty",
    "abaya kondotty",
    "women's clothes tirur",
    "ladies wear tirur",
    "abaya tirur",
    "women's clothes tirurangadi",
    "ladies wear tirurangadi",
    "women's clothes nilambur",
    "ladies wear nilambur",
    "women's clothes edappal",
    "women's clothes areacode",
    "women's clothes wandoor",
    "women's clothes ponnani",
    "women's clothes kottakkal",
    "women's clothes valanchery",
    "women's clothes pandikkad",
    "women's clothes melattur",
    "women's clothes vengara",
    "women's clothes parappanangadi",
    "women's clothes thanur",
    "women's clothes kuttippuram",
    "women's clothes mampad",
    "women's clothes pulamanthole",
    "women's clothes kalikavu",
    "women's clothes karuvarakundu",
    "women's clothes pookkottur",
    "women's clothes anakayam",
    "women's clothes makkaraparamba",
    "women's clothes thirurkkad",
    "women's clothes othukkungal",
    "women's clothes morayur",

    // Wider Kerala
    "ladies wear kerala",
    "women's wear kerala",
    "women's clothes kozhikode",
    "ladies wear kozhikode",
    "abaya kozhikode",
    "plus size kozhikode",
    "women's clothes calicut",
    "ladies wear calicut",
    "abaya calicut",
    "plus size calicut",
    "women's clothes wayanad",
    "women's clothes palakkad",
    "women's clothes thrissur",
    "women's clothes ernakulam",
    "women's clothes kochi",
    "women's clothes kannur",
    "women's clothes kasaragod",
    "women's clothes alappuzha",
    "women's clothes kollam",
    "women's clothes thiruvananthapuram",
    "women's clothes trivandrum",

    // ── Malayalam (native script) ──
    "സ്ത്രീകളുടെ വസ്ത്രം",
    "സ്ത്രീകളുടെ വസ്ത്രങ്ങൾ",
    "സ്ത്രീകളുടെ ഡ്രസ്സ്",
    "വനിതാ വസ്ത്രം",
    "വനിതാ ഫാഷൻ",
    "പെൺകുട്ടികളുടെ ഡ്രസ്സ്",
    "അനാർക്കലി ഓൺലൈൻ",
    "അനാർക്കലി ഡ്രസ്സ്",
    "അനാർക്കലി മഞ്ചേരി",
    "അനാർക്കലി മലപ്പുറം",
    "അബായ ഓൺലൈൻ",
    "അബായ മഞ്ചേരി",
    "അബായ മലപ്പുറം",
    "ബുർഖ ഓൺലൈൻ",
    "പർദ ഓൺലൈൻ",
    "ഹിജാബ് ഓൺലൈൻ",
    "ഷറാര",
    "ചുരിദാർ",
    "സൽവാർ",
    "ഗൗൺ",
    "ലെഹംഗ",
    "ദുപ്പട്ട",
    "വലിയ സൈസ് വസ്ത്രം",
    "പ്ലസ് സൈസ് ഡ്രസ്സ്",
    "കല്യാണ ഡ്രസ്സ്",
    "നിക്കാഹ് ഡ്രസ്സ്",
    "എൻഗേജ്മെന്റ് ഡ്രസ്സ്",
    "റിസപ്ഷൻ ഗൗൺ",
    "പെരുന്നാൾ ഡ്രസ്സ്",
    "ഈദ് ഡ്രസ്സ്",
    "റമദാൻ ഡ്രസ്സ്",
    "ഓണം ഡ്രസ്സ്",
    "ലേഡീസ് ഡ്രസ്സ്",
    "ലേഡീസ് വസ്ത്രം",
    "ലേഡീസ് ഫാഷൻ",
    "വനിതാ ഓൺലൈൻ ഷോപ്പിംഗ്",
    "വസ്ത്രം ഓൺലൈൻ",
    "ഡ്രസ്സ് ഓൺലൈൻ കേരളം",
    "കേരളം ഫാഷൻ",
    "മഞ്ചേരി ഫാഷൻ",
    "മലപ്പുറം ഷോപ്പിംഗ്",
    "മലപ്പുറം ഫാഷൻ",
    "മലപ്പുറം ലേഡീസ് വസ്ത്രം",
    "മലബാർ ഫാഷൻ",
    "മലബാർ ലേഡീസ് വസ്ത്രം",
    "mappila wedding dress",
    "malabar wedding dress",
    "malabar muslim dress",
    "malabar bridal dress",
    "malabar wedding lehenga",

    // ── Manglish (the way Malabar customers actually type) ──
    "udupp ladies online",
    "ladies udupp manjeri",
    "vasthram online",
    "vasthram manjeri",
    "vasthram malappuram",
    "vasthram online kerala",
    "ladies vasthram online",
    "ladies vasthram manjeri",
    "ponnungalude vasthram",
    "ponnungalude dress",
    "sthreekalude vasthram",
    "sthreekalude dress",
    "kalyana udupp",
    "kalyanam dress",
    "kalyana lehenga",
    "nikah dress online",
    "nikah lehenga",
    "nikah gown",
    "nikah anarkali",
    "nikah sharara",
    "perunnal dress",
    "perunnaal dress online",
    "perunnaal anarkali",
    "perunnaal abaya",
    "perunnal abaya",
    "ramadan abaya online",
    "ramadan dress online",
    "wedding udupp",
    "engagement udupp",
    "reception udupp",
    "mehendi dress online",
    "mehndi dress online",
    "haldi dress online",
    "modal udupp",
    "trendy udupp",
    "valiya size udupp",
    "valiya size dress",
    "valiya size abaya",
    "valiya size anarkali",
    "plus size udupp",
    "plus size vasthram",
    "malabar pengalude udupp",
    "mappila pengalude dress",
    "mappila ponnungal dress",
    "malappuram online udupp",
    "malappuram online vasthram",
    "manjeri online udupp",
    "kerala online udupp",
    "malayalee fashion",
    "malayali fashion online",

    // ── Plus size / big size special collection (the brand's hero category) ──
    "plus size women's clothing india",
    "plus size dresses india",
    "plus size dresses online india",
    "plus size anarkali online",
    "plus size anarkali india",
    "plus size anarkali xxxl",
    "plus size anarkali xxl",
    "plus size salwar suit",
    "plus size salwar kameez",
    "plus size sharara set",
    "plus size churidar online",
    "plus size kurta sets",
    "plus size kurti online",
    "plus size gown online",
    "plus size gown india",
    "plus size gown party wear",
    "plus size lehenga",
    "plus size wedding lehenga",
    "plus size bridal lehenga",
    "plus size party wear",
    "plus size party gown",
    "plus size cocktail dress",
    "plus size evening gown",
    "plus size formal wear",
    "plus size casual wear india",
    "plus size dress for women india",
    "plus size women xxxl",
    "plus size women xxxl india",
    "plus size xxxl dress",
    "plus size xxxl abaya",
    "plus size abaya online",
    "plus size abaya india",
    "plus size abaya xxxl",
    "plus size hijab abaya",
    "plus size islamic wear",
    "plus size modest wear",
    "plus size muslim wear",
    "plus size nikkah dress",
    "plus size eid dress",
    "plus size ramadan abaya",
    "plus size palazzo set",
    "plus size co-ord set",
    "plus size kaftan",
    "plus size maxi dress",
    "plus size midi dress",
    "plus size short dress",
    "plus size top",
    "plus size shirt",
    "plus size palazzo",
    "plus size skirt",
    "plus size jacket",
    "plus size jumpsuit",
    "plus size co ord",
    "plus size bottom wear",
    "plus size traditional wear",
    "plus size ethnic wear",
    "plus size ethnic dress",
    "plus size ethnic gown",
    "plus size designer wear",
    "plus size designer dress",
    "plus size designer gown",
    "plus size designer anarkali",
    "plus size designer abaya",
    "plus size handpicked",
    "plus size aesthetic dress",
    "plus size aesthetic clothing",
    "plus size aesthetic outfit",
    "plus size aesthetic anarkali",
    "plus size aesthetic abaya",
    "plus size aesthetic gown",
    "plus size aesthetic kurta",
    "plus size minimalist clothing",
    "curve fashion india",
    "curvy women clothing",
    "curvy fashion online india",
    "curvy women dresses",
    "curve girl fashion",
    "curve dress online",
    "curvy outfit india",
    "body positive fashion india",
    "inclusive fashion india",
    "size inclusive women's wear",
    "size inclusive online india",
    "size inclusive india",
    "size inclusive anarkali",
    "size inclusive abaya",
    "size inclusive plus size",
    "plus size brand india",
    "plus size online shopping india",
    "plus size shopping",
    "plus size online store",
    "plus size store online",
    "plus size shop online india",
    "big size dress for women",
    "big size dress online india",
    "big size dress online",
    "big size anarkali online",
    "big size salwar online",
    "big size churidar online",
    "big size sharara online",
    "big size gown online",
    "big size lehenga online",
    "big size dupatta",
    "big size kurta",
    "big size kurti",
    "big size abaya",
    "big size hijab abaya",
    "big size women's wear",
    "big size women's dress",
    "big size women's clothing",
    "big size women's clothes",
    "big size ladies dress",
    "big size ladies clothes",
    "big size ladies wear",
    "big size aesthetic dress",
    "big size aesthetic anarkali",
    "big size party wear",
    "big size party gown",
    "big size party dress",
    "big size wedding dress",
    "big size wedding gown",
    "big size wedding lehenga",
    "big size wedding anarkali",
    "big size wedding sharara",
    "big size eid dress",
    "big size eid abaya",
    "big size ramadan abaya",
    "big size nikkah dress",
    "big size nikkah anarkali",
    "big size nikkah gown",
    "big size nikkah lehenga",
    "big size mehendi dress",
    "big size reception gown",
    "big size engagement dress",
    "big size designer wear",
    "big size store online",
    "big size shop manjeri",
    "big size store malappuram",
    "big size women fashion kerala",
    "big size women fashion india",
    "xxxl women clothing",
    "xxxl women dress",
    "xxxl anarkali",
    "xxxl abaya",
    "xxxl gown",
    "xxxl kurta",
    "xxxl salwar",
    "xxxl sharara",
    "xxxl churidar",
    "xxxl women's wear",
    "xxxl bridal wear",
    "xxxl wedding gown",
    "xxl women clothing",
    "xxl anarkali",
    "xxl abaya",
    "xxl gown",
    "4xl women's wear",
    "4xl anarkali",
    "4xl abaya",
    "5xl women's wear",
    "5xl abaya",
    "5xl anarkali",
    "6xl abaya",
    "fat ladies dress",
    "plump women dress",
    "heavy women dress",
    "heavy size women clothing",
    "fluffy women clothing",
    "fluffy fashion india",
    "plus size kerala",
    "plus size manjeri",
    "plus size malappuram",
    "plus size online kerala",
    "plus size store kerala",
    "plus size shop kerala",
    "plus size store manjeri",
    "plus size shop manjeri 2",
    "plus size shop malappuram",
    "plus size store malappuram",
    "plus size brand kerala",
    "plus size designer kerala",
    "plus size aesthetic kerala",
    "big size online kerala",
    "big size store kerala",
    "big size shop kerala",
    "big size online manjeri",
    "big size online malappuram",
    "big size brand kerala",
    "plus size muslim wear india",
    "plus size muslim wear kerala",
    "plus size islamic wear india",
    "plus size modest dress india",
    "plus size aesthetic muslim wear",
    "plus size for tall women",
    "plus size for short women",

    // ── Anarkali ──
    "anarkali suit online",
    "anarkali dress online",
    "anarkali gown online",
    "anarkali set online",
    "anarkali kurta",
    "anarkali long",
    "anarkali floor length",
    "anarkali frock",
    "anarkali designer",
    "anarkali wedding",
    "anarkali bridal",
    "anarkali engagement",
    "anarkali nikkah",
    "anarkali eid",
    "anarkali ramadan",
    "anarkali party wear",
    "anarkali festive",
    "anarkali embroidered",
    "anarkali zari work",
    "anarkali sequin",
    "anarkali pastel",
    "anarkali black",
    "anarkali maroon",
    "anarkali wine",
    "anarkali green",
    "anarkali blue",
    "anarkali pink",
    "anarkali peach",
    "anarkali nude",
    "anarkali ivory",
    "anarkali white",
    "anarkali velvet",
    "anarkali silk",
    "anarkali georgette",
    "anarkali cotton",
    "anarkali chiffon",
    "anarkali net",
    "anarkali kalidar",
    "anarkali umbrella cut",
    "anarkali a-line",
    "anarkali set with dupatta",
    "anarkali set with palazzo",
    "anarkali set with churidar",
    "anarkali kurta set",
    "anarkali for women",
    "anarkali for plus size women",
    "anarkali for big size women",
    "anarkali for tall women",
    "anarkali pakistani",
    "anarkali indian",

    // ── Salwar / Kameez / Churidar / Sharara ──
    "salwar suit online",
    "salwar kameez online",
    "salwar suit india",
    "salwar kameez india",
    "salwar suit pakistani",
    "salwar suit punjabi",
    "salwar suit cotton",
    "salwar suit silk",
    "salwar suit designer",
    "salwar suit embroidered",
    "salwar suit party wear",
    "salwar suit wedding",
    "salwar suit casual",
    "salwar suit plus size",
    "salwar suit big size",
    "salwar suit xxxl",
    "salwar set",
    "salwar pant",
    "salwar palazzo",
    "salwar churidar",
    "salwar dupatta",
    "churidar set online",
    "churidar suit online",
    "churidar designer",
    "churidar embroidered",
    "churidar plus size",
    "churidar big size",
    "churidar xxxl",
    "churidar wedding",
    "churidar nikkah",
    "churidar party wear",
    "churidar bottom",
    "churidar leggings",
    "churidar kurta set",
    "sharara suit online",
    "sharara set online",
    "sharara designer",
    "sharara wedding",
    "sharara nikkah",
    "sharara eid",
    "sharara plus size",
    "sharara big size",
    "sharara xxxl",
    "sharara pakistani",
    "sharara cotton",
    "sharara silk",
    "sharara georgette",
    "sharara embroidered",
    "sharara mirror work",
    "sharara kameez",

    // ── Gown / Lehenga / Bridal ──
    "gown online india",
    "gown for women india",
    "gown party wear",
    "gown wedding",
    "gown reception",
    "gown engagement",
    "gown nikkah",
    "gown evening",
    "gown cocktail",
    "gown ball",
    "gown long",
    "gown maxi",
    "gown floor length",
    "gown a-line",
    "gown plus size",
    "gown big size",
    "gown xxxl",
    "gown designer",
    "gown embroidered",
    "gown sequin",
    "gown velvet",
    "gown silk",
    "gown georgette",
    "gown cape",
    "gown indo-western",
    "gown muslim wear",
    "gown abaya style",
    "lehenga online india",
    "lehenga choli",
    "lehenga wedding",
    "lehenga bridal",
    "lehenga sister of bride",
    "lehenga nikkah",
    "lehenga reception",
    "lehenga engagement",
    "lehenga sangeet",
    "lehenga mehndi",
    "lehenga haldi",
    "lehenga embroidered",
    "lehenga zari",
    "lehenga sequin",
    "lehenga mirror work",
    "lehenga plus size",
    "lehenga big size",
    "lehenga xxxl",
    "lehenga designer",
    "lehenga pastel",
    "lehenga maroon",
    "lehenga blue",
    "lehenga green",

    // ── Abaya / Hijab / Burqa / Islamic wear (massive in Malabar) ──
    "abaya online india",
    "abaya online kerala",
    "abaya online malappuram",
    "abaya online manjeri",
    "abaya designer",
    "abaya designer india",
    "abaya dubai style",
    "abaya black",
    "abaya colored",
    "abaya pastel",
    "abaya open",
    "abaya closed",
    "abaya butterfly",
    "abaya kaftan",
    "abaya kimono",
    "abaya bisht",
    "abaya umbrella",
    "abaya layered",
    "abaya embroidered",
    "abaya sequin",
    "abaya stone work",
    "abaya mirror work",
    "abaya cuff",
    "abaya wedding",
    "abaya nikkah",
    "abaya bridal",
    "abaya for bride",
    "abaya party wear",
    "abaya eid",
    "abaya ramadan",
    "abaya iftar",
    "abaya hajj",
    "abaya umrah",
    "abaya prayer",
    "abaya everyday",
    "abaya casual",
    "abaya formal",
    "abaya office",
    "abaya college",
    "abaya school",
    "abaya plus size",
    "abaya big size",
    "abaya xxxl",
    "abaya 4xl",
    "abaya 5xl",
    "abaya for tall women",
    "abaya for short women",
    "abaya stitched",
    "abaya unstitched",
    "abaya hijab set",
    "abaya hijab combo",
    "abaya with hijab",
    "abaya with niqab",
    "abaya with shayla",
    "burqa online india",
    "burqa online kerala",
    "burqa online malappuram",
    "burqa online manjeri",
    "burqa designer",
    "burqa modern",
    "burqa stylish",
    "burqa plus size",
    "burqa big size",
    "burqa xxxl",
    "burqa wedding",
    "burqa nikkah",
    "burqa eid",
    "purdah online",
    "purdah designer",
    "purdah modern",
    "purdah plus size",
    "purdah xxxl",
    "hijab online india",
    "hijab online kerala",
    "hijab online malappuram",
    "hijab online manjeri",
    "hijab cotton",
    "hijab chiffon",
    "hijab silk",
    "hijab georgette",
    "hijab printed",
    "hijab plain",
    "hijab wedding",
    "hijab nikkah",
    "hijab eid",
    "hijab daily wear",
    "hijab combo",
    "hijab abaya combo",
    "hijab pin",
    "hijab inner cap",
    "niqab online",
    "niqab plain",
    "niqab designer",
    "shayla online",
    "khimar online",
    "khimar plain",
    "khimar designer",
    "khimar plus size",
    "jilbab online",
    "jilbab plus size",

    // ── Modest fashion ──
    "modest fashion india",
    "modest fashion kerala",
    "modest fashion online",
    "modest dress online",
    "modest dress india",
    "modest dress kerala",
    "modest dress muslim",
    "modest wear india",
    "modest wear kerala",
    "modest wear online",
    "modest wear muslim women",
    "modest wear plus size",
    "modest wear big size",
    "modest gown",
    "modest gown online",
    "modest anarkali",
    "modest abaya",
    "modest kurta",
    "modest dress for women",
    "modest dress muslim india",
    "modest fashion kerala muslim",
    "muslim women's clothing india",
    "muslim women's wear india",
    "muslim women's dress online",
    "muslim women's fashion",
    "muslim wedding dress online",
    "muslim bridal wear",
    "muslim bridal anarkali",
    "muslim bridal lehenga",
    "muslim bridal gown",
    "muslim bridal abaya",
    "muslim bridal sharara",
    "muslim wedding dress kerala",
    "muslim wedding dress malabar",
    "muslim wedding dress malappuram",
    "muslim wedding dress manjeri",
    "muslim wedding dress mappila",
    "mappila wedding outfit",
    "mappila bridal outfit",
    "mappila pengalude udupp 2",
    "mappila ponnungal dress 2",
    "islamic wear india",
    "islamic clothing india",
    "islamic wear online",
    "islamic wear kerala",
    "islamic wear muslim women",
    "islamic dress online",
    "islamic dress for women",
    "islamic dress plus size",
    "islamic clothing plus size",

    // ── Indo-Western / Fusion ──
    "indo-western for women",
    "indo-western dress",
    "indo-western gown",
    "indo-western tunic",
    "indo-western kurta",
    "indo-western online india",
    "fusion wear india",
    "fusion dress online",
    "fusion gown india",
    "fusion anarkali",
    "fusion abaya",
    "fusion kurta",
    "fusion tunic",
    "fusion sharara",
    "fusion outfit india",
    "fusion outfit muslim",
    "fusion party wear",
    "fusion plus size",
    "fusion big size",
    "fusion modest wear",
    "fusion ethnic wear",
    "fusion muslim wear",

    // ── Dupatta / accessories ──
    "dupatta online",
    "dupatta cotton",
    "dupatta silk",
    "dupatta net",
    "dupatta heavy work",
    "dupatta embroidered",
    "dupatta wedding",
    "dupatta for plus size",
    "dupatta long",
    "dupatta short",
    "stole online",
    "shawl online",
    "scarf online india",
    "scarf online kerala",

    // ── Wedding / nikkah / engagement / reception / festive occasion ──
    "wedding dress for women india",
    "wedding dress online",
    "wedding gown online",
    "wedding gown india",
    "wedding gown plus size",
    "wedding gown big size",
    "wedding gown xxxl",
    "wedding lehenga online",
    "wedding anarkali online",
    "wedding sharara online",
    "wedding sharara plus size",
    "wedding gown muslim",
    "wedding gown malabar",
    "nikkah dress online",
    "nikkah dress for bride",
    "nikkah dress plus size",
    "nikkah dress xxxl",
    "nikkah anarkali",
    "nikkah lehenga",
    "nikkah gown",
    "nikkah sharara",
    "nikkah abaya",
    "engagement dress online",
    "engagement gown online",
    "engagement anarkali",
    "engagement lehenga",
    "engagement plus size",
    "reception gown online",
    "reception lehenga",
    "reception dress plus size",
    "reception dress big size",
    "reception gown plus size",
    "mehendi dress online 2",
    "mehndi dress online 2",
    "mehendi outfit",
    "mehndi outfit",
    "haldi outfit",
    "sangeet outfit",
    "eid outfit",
    "eid dress online",
    "eid dress for women",
    "eid dress plus size",
    "eid dress big size",
    "eid abaya online",
    "eid anarkali online",
    "eid sharara online",
    "eid kurta set",
    "eid 2026 outfit",
    "eid 2026 dress",
    "eid 2026 abaya",
    "eid 2026 anarkali",
    "ramadan dress online 2",
    "ramadan abaya online 2",
    "ramadan outfit",
    "ramadan kurta",
    "ramadan eid combo",
    "iftar dress",
    "iftar abaya",
    "onam dress",
    "onam saree",
    "onam kurta set",
    "onam outfit kerala",
    "vishu dress",
    "christmas dress online",

    // ── Generic women's fashion / India online ──
    "women's online clothing india",
    "ladies online clothing india",
    "women's fashion online india",
    "ladies fashion online india",
    "women's online shopping india",
    "ladies online shopping india",
    "trendy women clothing india",
    "trendy ladies fashion",
    "designer dress online india",
    "designer wear online india",
    "designer collection women",
    "premium women clothing india",
    "luxury women fashion india",
    "boutique online india",
    "boutique online kerala",
    "boutique online malappuram",
    "boutique online manjeri",
    "ethnic wear online india",
    "ethnic wear for women",
    "ethnic wear kerala",
    "ethnic dress online",
    "ethnic gown online",
    "ethnic anarkali",
    "ethnic salwar",
    "ethnic sharara",
    "ethnic abaya",
    "fashion store online india",
    "fashion store kerala",
    "fashion store malappuram online",
    "fashion store manjeri online",
    "women clothing brand india",
    "women clothing brand kerala",
    "women clothing brand malappuram",
    "ladies clothing brand kerala",
    "women apparel online india",
    "women apparel kerala",
    "women apparel malappuram",
    "women apparel manjeri",
    "trendy outfits women",
    "trendy outfits girls",
    "premium fashion india",
    "premium fashion kerala",
    "minimalist fashion india",
    "minimalist fashion women",
    "aesthetic fashion india",
    "aesthetic clothing india",
    "aesthetic clothing women",
    "aesthetic clothing kerala",
    "aesthetic clothing online",
    "aesthetic outfit india",

    // ── "Near me" / long-tail / comparison queries ──
    "women's clothing near me",
    "ladies wear near me",
    "abaya shop near me",
    "anarkali shop near me",
    "plus size shop near me",
    "big size shop near me",
    "boutique near me",
    "dress shop near me",
    "wedding dress shop near me",
    "bridal shop near me",
    "modest wear near me",
    "muslim wear near me",
    "islamic clothing near me",
    "fashion store near me",
    "women's boutique near me",
    "women's clothing near manjeri",
    "women's clothing near malappuram",
    "women's clothing near perinthalmanna",
    "women's clothing near kondotty",
    "women's clothing near tirur",
    "abaya shop near manjeri",
    "abaya shop near malappuram",
    "plus size shop near manjeri",
    "plus size shop near malappuram",
    "big size shop near manjeri",
    "big size shop near malappuram",
    "nikkah dress shop near me",
    "wedding lehenga shop near me",
    "ramadan abaya near me",
    "eid abaya near me",
    "boutique near manjeri",
    "boutique near malappuram",
    "boutique near perinthalmanna",
    "fashion store near manjeri",
    "fashion store near malappuram",
    "women clothing online malappuram delivery",
    "women clothing online manjeri delivery",
    "abaya online malappuram delivery",
    "abaya online manjeri delivery",
    "anarkali online kerala delivery",
    "plus size online kerala delivery",
    "plus size aesthetic dress kerala",
    "plus size aesthetic abaya kerala",
    "xxxl abaya online india delivery",
    "xxxl anarkali online india delivery",
    "best plus size store india",
    "best plus size brand india",
    "best plus size brand kerala",
    "best plus size brand malabar",
    "best abaya store kerala",
    "best abaya store manjeri",
    "best abaya brand india",
    "best abaya brand kerala",
    "best women fashion store malappuram",
    "best women fashion store manjeri",
    "best women fashion brand kerala",
    "best modest wear brand india",
    "best modest fashion store kerala",
    "best islamic wear brand india",
    "best wedding dress shop manjeri",
    "best wedding dress shop malappuram",
    "best nikkah dress shop kerala",
    "best mappila wedding dress",
    "best malabar wedding dress",
    "best muslim wedding store kerala",
    "best ramadan abaya brand",
    "best eid abaya store kerala",

    // ── Arabic-script + extra Malayalam compounds ──
    "عباية",
    "عباية ملايو",
    "عباية للزفاف",
    "عباية مقاس كبير",
    "عباية أنيقة",
    "ഈദ് മുബാറക്ക് ഡ്രസ്സ്",
    "ഈദ് ഡ്രസ്സ് ഓൺലൈൻ",
    "ഈദ് അബായ",
    "ഈദ് അനാർക്കലി",
    "നിക്കാഹ് ഗൗൺ",
    "നിക്കാഹ് അനാർക്കലി",
    "നിക്കാഹ് ലെഹംഗ",
    "നിക്കാഹ് അബായ",
    "പെരുന്നാൾ അബായ",
    "പെരുന്നാൾ അനാർക്കലി",
    "കല്യാണ ഗൗൺ",
    "കല്യാണ അനാർക്കലി",
    "കല്യാണ ലെഹംഗ",
    "കല്യാണ ഷറാര",
    "കല്യാണ അബായ",
    "വലിയ സൈസ് അബായ",
    "വലിയ സൈസ് അനാർക്കലി",
    "വലിയ സൈസ് ഗൗൺ",
    "വലിയ സൈസ് ലെഹംഗ",
    "വലിയ സൈസ് ഷറാര",
    "plus size pengalude udupp",
    "plus size mappila pengalude udupp",
    "valiya size pengalude udupp",
    "malappuram pengalude online udupp",
    "manjeri pengalude online udupp",
    "kerala pengalude online udupp",
    "malabar pengalude udupp online",
    "vami clubwear shop online india",
  ],
  authors: [{ name: 'Vami Clubwear' }],
  creator: 'Vami Clubwear',
  publisher: 'Vami Clubwear',
  alternates: {
    canonical: SITE_URL,
  },
  formatDetection: { email: false, address: false, telephone: false },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    alternateLocale: ['ml_IN', 'hi_IN', 'ar'],
    url: SITE_URL,
    siteName: 'Vami Clubwear',
    title: "Vami Clubwear — Women's Fashion in Malappuram, Manjeri | Plus Size, Anarkali, Abaya",
    description:
      "Premium women's fashion store in Malappuram & Manjeri. Plus size & big size Anarkalis, abayas, salwars, gowns up to XXXL — modest, Malabar wedding & Indo-Western wear.",
    images: [
      {
        url: '/hero-models.webp',
        width: 1200,
        height: 630,
        alt: "Vami Clubwear — women's fashion store in Malappuram, Manjeri",
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: "Vami Clubwear — Women's Fashion in Malappuram, Manjeri",
    description:
      "Plus size & big size Anarkalis, abayas, salwars, gowns up to XXXL. Modest, Malabar wedding & Indo-Western wear, shipped across India.",
    images: ['/hero-models.webp'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  icons: {
    icon: '/icon.svg',
    shortcut: '/logo-icon.svg',
    apple: '/logo-icon.svg',
  },
  verification: {
    // Replace with the real Search Console token. Leaving the placeholder file
    // (`google5b124ff02ad846fb.html`) in /public covers the legacy file-based path.
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  },
}

const ORG_JSONLD = {
  '@context': 'https://schema.org',
  '@type': 'ClothingStore',
  '@id': `${SITE_URL}/#organization`,
  name: 'Vami Clubwear',
  alternateName: ['Vami', 'Vami Manjeri', 'Vami Clubwear Manjeri', 'വാമി', 'വാമി ക്ലബ്‌വെയർ'],
  url: SITE_URL,
  logo: `${SITE_URL}/logo.svg`,
  image: `${SITE_URL}/hero-models.webp`,
  description:
    "Premium women's fashion store in Malappuram & Manjeri, Kerala — plus size & big size aesthetic Anarkalis, abayas, salwars, shararas, churidars, gowns and dupattas up to XXXL. Indo-Western fusion, modest fashion and Malabar wedding wear, shipped across India.",
  slogan: "Aesthetic plus-size & modest fashion from Malabar",
  knowsLanguage: ['en', 'ml', 'hi', 'ar'],
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Manjeri',
    addressRegion: 'Kerala',
    postalCode: '676121',
    addressCountry: 'IN',
  },
  areaServed: [
    { '@type': 'City', name: 'Manjeri' },
    { '@type': 'City', name: 'Malappuram' },
    { '@type': 'City', name: 'Perinthalmanna' },
    { '@type': 'City', name: 'Kondotty' },
    { '@type': 'City', name: 'Tirur' },
    { '@type': 'City', name: 'Tirurangadi' },
    { '@type': 'City', name: 'Nilambur' },
    { '@type': 'City', name: 'Edappal' },
    { '@type': 'City', name: 'Ponnani' },
    { '@type': 'City', name: 'Kottakkal' },
    { '@type': 'City', name: 'Kozhikode' },
    { '@type': 'AdministrativeArea', name: 'Malappuram District' },
    { '@type': 'AdministrativeArea', name: 'Malabar' },
    { '@type': 'State', name: 'Kerala' },
    { '@type': 'Country', name: 'India' },
  ],
  sameAs: [
    'https://www.instagram.com/vami_clubwear_manjeri/',
  ],
}

const WEBSITE_JSONLD = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${SITE_URL}/#website`,
  name: 'Vami Clubwear',
  alternateName: ['Vami', 'Vami Manjeri', 'Vami Clubwear Manjeri'],
  url: SITE_URL,
  inLanguage: ['en-IN', 'ml-IN'],
  publisher: { '@id': `${SITE_URL}/#organization` },
  potentialAction: {
    '@type': 'SearchAction',
    target: `${SITE_URL}/search?q={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
}

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
  colorScheme: 'light',
  width: 'device-width',
  initialScale: 1,
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://res.cloudinary.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://res.cloudinary.com" />
        {/* Preconnect to the backend so the first /api call doesn't pay a TCP+TLS handshake */}
        <link rel="preconnect" href="https://api.vamiclubwear.in" crossOrigin="" />
        <link rel="dns-prefetch" href="https://api.vamiclubwear.in" />
        {/* Preload the body weight of Metropolis so first paint isn't served in the fallback font */}
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="/fonts/metropolis/metropolis-latin-400-normal.woff2"
          crossOrigin=""
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(ORG_JSONLD) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(WEBSITE_JSONLD) }}
        />
      </head>
      <body className={`min-h-screen bg-background text-on-background ${poppins.variable}`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
